.TH MACSSHD 1 "May 25, 2011"
.SH NAME
macsshd \- Daemon for tunneling SSH protocol through MAC-address connections.
.SH SYNOPSIS
.B macsshd
.RI [ options ]
.SH DESCRIPTION
This daemon listens for ssh connections from macssh clients on the same physical network. It also announces it's hostname via the MNDP protocol every minute.
.SH OPTIONS
These programs follow the usual GNU command line syntax.
A summary of options is included below.
.TP
.B \-n
Do not use broadcast packets. A tad less insecure.
This means that ethernet packets will have the mac-address of the client as the packet
destination, instead of using the ethernet broadcast address.
.TP
.B \-p
Destination port. The ssh connections will be forwarded to ssh daemon on this local port.
Without this option the connections will be forwarded to port 22.
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.SH SEE ALSO
.BR mndp (1),
.BR mactelnet (1),
.BR macping (1),
.BR macssh (1),
.SH AUTHOR
macsshd is a derived work by Ali Onur Uyar <aouyar@gmail.com> based on macsshd by Håkon Nessjøen <haakon.nessjoen@gmail.com>.
.PP
This manual page was written by Ali Onur Uyar <aouyar@gmail.com> based on manual page for mactelnet by Håkon Nessjøen <haakon.nessjoen@gmail.com>,
for the Debian project (and may be used by others).
mactelnetd was written by Håkon Nessjøen <haakon.nessjoen@gmail.com>.
